apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "mydatabase"
  POSTGRES_HOST: "postgres-service" # The hostname will match the Postgres service name
  POSTGRES_PORT: "5432"
